### ISSUE TITLE
Exception queue.Empty

### ISSUE THREAD

**Issue by PaulKarlshoeferBULL** [vecma-project/EasyVVUQ-QCGPJ#24]
Dear Vecma team:)

An exception was raised today, that I havn't seend before.
Setup: 20 nodes, 48 tasks_per_node, 6400 pilot-jobs, 
Machine: SM NG, general partition

What went wrong?

**Exception**
```
Traceback (most recent call last):
  File "/dss/dsshome1/03/di67piq/Vecma/install/lib/python3.6/site-packages/qcg/pilotjob/service.py", line 531, in run
    self.service = QCGPMService(self.args)
  File "/dss/dsshome1/03/di67piq/Vecma/install/lib/python3.6/site-packages/qcg/pilotjob/service.py", line 246, in __init__
    self._setup_direct_manager(self._args.parent)
  File "/dss/dsshome1/03/di67piq/Vecma/install/lib/python3.6/site-packages/qcg/pilotjob/service.py", line 276, in _setup_direct_manager
    self._manager = DirectManager(self._conf, parent_manager)
  File "/dss/dsshome1/03/di67piq/Vecma/install/lib/python3.6/site-packages/qcg/pilotjob/manager.py", line 432, in __init__
    self._executor = Executor(self, conf, self.resources)
  File "/dss/dsshome1/03/di67piq/Vecma/install/lib/python3.6/site-packages/qcg/pilotjob/executor.py", line 66, in __init__
    raise exc
  File "/dss/dsshome1/03/di67piq/Vecma/install/lib/python3.6/site-packages/qcg/pilotjob/executor.py", line 61, in __init__
    self._resources.binding)
  File "/dss/dsshome1/03/di67piq/Vecma/install/lib/python3.6/site-packages/qcg/pilotjob/executionjob.py", line 342, in start_agents
    asyncio.get_event_loop().run_until_complete(asyncio.ensure_future(cls.launcher.start(agents)))
  File "/dss/dsshome1/03/di67piq/Vecma/install/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "/dss/dsshome1/03/di67piq/Vecma/install/lib/python3.6/site-packages/qcg/pilotjob/launcher/launcher.py", line 107, in start
    await self.__fire_agents(instances)
  File "/dss/dsshome1/03/di67piq/Vecma/install/lib/python3.6/site-packages/qcg/pilotjob/launcher/launcher.py", line 313, in __fire_agents
    raise Exception('timeout while waiting for agents')
Exception: timeout while waiting for agents
Traceback (most recent call last):
  File "/dss/dsshome1/03/di67piq/Vecma/install/lib/python3.6/site-packages/qcg/pilotjob/api/manager.py", line 682, in __init__
    self.qcgpm_conf = self.qcgpm_queue.get(block=True, timeout=600)
  File "/dss/dsshome1/03/di67piq/Vecma/install/lib/python3.6/multiprocessing/queues.py", line 105, in get
    raise Empty
queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./tests/test_bench.py", line 174, in <module>
    stats = test_cooling_pj(r, o)
  File "./tests/test_bench.py", line 109, in test_cooling_pj
    qcgpjexec.create_manager(log_level='debug')
  File "/dss/dsshome1/03/di67piq/Vecma/install/lib/python3.6/site-packages/eqi/core/executor.py", line 103, in create_manager
    self._qcgpjm = LocalManager(args, client_conf)
  File "/dss/dsshome1/03/di67piq/Vecma/install/lib/python3.6/site-packages/qcg/pilotjob/api/manager.py", line 684, in __init__
    raise errors.ServiceError('Service not started - timeout')
qcg.pilotjob.api.errors.ServiceError: Service not started - timeout

```

**Comment by pkopta** [comment]
Hi Paul,
The error you encounter is raised when local launchers started by QCG-PilotJob didn't register in the service in specific time after start. The local launchers are sub-services used by QCG-PilotJob to directly launch (currently) single core tasks on remote nodes without communication with Slurm. The timeout for launchers register in service is set in class qcg.pilotjob.launcher.Launcher  as START_TIMEOUT_SECS variable with value 600 - 10 minutes. It means that the launcher processes wasn't properly start by Slurm or there was some communication problem between nodes in allocation. The problem can be debugged by using '--log debug' QCG-PilotJob option - the files 'nl-ID-start-agent-stoud.log' and 'nl-ID-start-agent-stderr.log' files should be created in '.qcgpjm_' subdirectory with stdout/stderr from local launchers. There is also an option '--disable-nl' in QCG-PilotJob which disables local laucher mechasnim - in this case all jobs will be executed via Slurm.

**Comment by PaulKarlshoeferBULL** [comment]
Thank you for your answer. To me, the issue seems to appear somewhat randomly. Some runs fail, while others get through (with exact same settings and code). Is it an issue with slurm, then?
